language: php

sudo: false

cache:
  - directories:
      - $HOME/.composer/cache/files

php: [ 7.1, 8, hhvm ]

before_install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - phpunit --configuration ./tests/phpunit.xml.dist
  # Test dev-master install
  - cd "$TRAVIS_BUILD_DIR/tests/example-latest-version" && composer install -vvv --profile
  #- ls -ashF bin
  #- bin/electron -v
  # Test v16.0.0 install
  - cd "$TRAVIS_BUILD_DIR/tests/example-v16.0.0" && composer install -vvv --profile
  #- ls -ashF bin
  #- bin/electron -v
